import express from "express";
var router = express.Router();
import bodyParser from 'body-parser';
// var bodyParser = require('body-parser');
import dotenv from 'dotenv';
 dotenv.config();
// import  sendMessage  from "../messageHelper.js";
import axios from 'axios';

function sendMessage(data) {
  var config = {
    method: 'post',
    url: `https://graph.facebook.com/${process.env.VERSION}/${process.env.PHONE_NUMBER_ID}/messages`,
    headers: {
      'Authorization': `Bearer ${process.env.ACCESS_TOKEN}`,
      'Content-Type': 'application/json'
    },
    data: data
  };

  return axios(config)
}
function getTextMessageInput(recipient, text) {
    return JSON.stringify({
      "messaging_product": "whatsapp",
      "preview_url": false,
      "recipient_type": "individual",
      "to": recipient,
      "type": "text",
      "text": {
          "body": text
      }
    });
    
  }
// import getTextMessageInput from "../messageHelper.js";
// const { sendMessage, getTextMessageInput } = require("../messageHelper");

router.use(bodyParser.json());



router.post('/', (req, res, next)=> {
   
  var data = getTextMessageInput(process.env.RECIPIENT_WAID, 'This is the message generated by prakhars web dev project');
//   console.log(data);
  sendMessage(data)
    .then(function (response) {
    //   res.redirect('/');
      res.sendStatus(200);
      return;
    })
    .catch(function (error) {
      console.log(error);
    //   console.log(error.response.data);
      res.sendStatus(500);
      return;
    });
});

export default router;